[package]
name = "ontology-mapper-producer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lbd-pipeline = { workspace = true }
lbd-ontology = { workspace = true }
lbd-converter = { workspace = true }
structured-data = { path = "../structured-data" }
rio_api = { workspace = true }
rio_turtle = { workspace = true }
oxiri = "0.2"
