#!/usr/bin/env python3
"""Generate the IFC class -> quantity-set table from the vendored bSDD index.

`plugin-qto-preprocess` used to carry a hand-written table covering 14 IFC types,
whose fallback for everything else asked for a single `GrossVolume`. That is why
`IfcBuildingElementProxy` — and railings, stairs, coverings, members and ~1,000
other classes — never received the quantities they are defined to have.

bSDD already knows the answer, and the index is already vendored for the bSDD
matcher. This script projects it into a table the plugin embeds:

    <ifc_class>\t<Qto_SetName>\t<Quantity>,<Quantity>,...

Regenerate after bumping the bSDD index:

    python3 scripts/build_qto_index.py

Two filters are applied, both deliberate:

* `Qto_BodyGeometryValidation` is dropped. It is a validation set
  (`SurfaceGenusBeforeFeatures` and similar), not base quantities.
* Quantities that geometry alone cannot yield are dropped — see
  NON_GEOMETRIC. Asking for a mass without a density would guarantee a
  permanent coverage miss and obscure the ones that matter.
"""

from __future__ import annotations

import gzip
import json
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX = REPO_ROOT / "crates" / "lbd-converter" / "resources" / "bsdd_ifc4x3_index.json.gz"
OUTPUT = REPO_ROOT / "crates" / "plugin-qto-preprocess" / "resources" / "qto_sets.tsv"

VALIDATION_SET = "qtobodygeometryvalidation"

# Needs material density, occurrence counts or earthwork state — not derivable
# from the solid.
NON_GEOMETRIC = {
    "GrossWeight",
    "NetWeight",
    "Weight",
    "Mass",
    "Count",
    "NumberOfGangs",
    "LooseVolume",
    "CompactedVolume",
    "UndisturbedVolume",
}

# bSDD IFC4x3 spells these with a capital P; every model in the validation corpus
# authors the IFC4 lowercase-p form (504 instances). Emitting bSDD's spelling
# would make the audit's name comparison miss and *duplicate* the quantity
# instead of filling it, so the IFC4 spelling wins.
SPELLING = {
    "GrossFootPrintArea": "GrossFootprintArea",
    "NetFootPrintArea": "NetFootprintArea",
    "FootPrintArea": "FootprintArea",
}

# 997 classes carry a Qto set, but 499 of them (actuators, alarms, controllers
# and similar MEP devices) define only GrossWeight/Count, which geometry cannot
# give. Those drop out entirely, leaving ~498.
MIN_CLASSES = 450


def canonical(name: str) -> str:
    return SPELLING.get(name, name)


def main() -> int:
    if not INDEX.is_file():
        print(f"error: bSDD index missing at {INDEX}", file=sys.stderr)
        return 1

    data = json.loads(gzip.open(INDEX, "rt", encoding="utf-8").read())
    exact = data["exact"]

    # class -> set -> ordered unique quantity names
    by_class: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for key, prop in exact.items():
        cls, set_name, _ = key.split("|", 2)
        if not set_name.startswith("qto") or set_name == VALIDATION_SET:
            continue
        name = canonical(prop)
        if name in NON_GEOMETRIC:
            continue
        bucket = by_class[cls][set_name]
        if name not in bucket:
            bucket.append(name)

    # bSDD keys are normalised (lowercase, no underscores). `class_code_by_norm`
    # maps them back to the canonical code, which is authoritative — the human
    # `name` field is prose ("Quantity Set: Wall Base Quantities") and must not be
    # used to reconstruct it.
    codes = data.get("class_code_by_norm", {})

    rows: list[tuple[str, str, list[str]]] = []
    for cls, sets in sorted(by_class.items()):
        for set_norm, quantities in sorted(sets.items()):
            if not quantities:
                continue
            display = display_set_name(set_norm, codes)
            rows.append((cls, display, quantities))

    if len({c for c, _, _ in rows}) < MIN_CLASSES:
        print(
            f"error: only {len({c for c, _, _ in rows})} classes extracted, "
            f"expected >= {MIN_CLASSES}. The index layout probably changed.",
            file=sys.stderr,
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        f.write("# generated by scripts/build_qto_index.py — do not edit\n")
        f.write("# <ifc_class>\\t<Qto_SetName>\\t<comma-separated quantities>\n")
        for cls, set_name, quantities in rows:
            f.write(f"{cls}\t{set_name}\t{','.join(quantities)}\n")

    classes = len({c for c, _, _ in rows})
    print(f"wrote {len(rows)} rows covering {classes} IFC classes to "
          f"{OUTPUT.relative_to(REPO_ROOT)}")
    return 0


def display_set_name(set_norm: str, codes: dict) -> str:
    """`qtowallbasequantities` -> `Qto_WallBaseQuantities`."""
    code = codes.get(set_norm)
    if isinstance(code, str) and code:
        return code
    raise KeyError(
        f"no canonical code for quantity set {set_norm!r}; refusing to guess a "
        f"set name that would be written into models"
    )


if __name__ == "__main__":
    raise SystemExit(main())
